### PR TITLE
feat(private_endpoint.tf) allow custom location on private-endpoint

### PR DESCRIPTION
**Pull request by matthiasritter**
## Describe your changes
The default location for the private-endpoint is calculated from the resource-group of the VNET.
Since there could be another VNET in another region in the same resource-group, we need the ability to specify the location from the VNET or a custom location

### CODE REVIEW

**Comment by matthiasritter** [comment]
Hi @zioproto could you take a look at this PR?
Let me know if there is something that should be changed, according your guidlines

**Comment by zioproto** [comment]
Hello, it seems you did not run the `pre-commit` and `pr-check` steps. Please read the readme file at the section contributing:

https://github.com/Azure/terraform-azurerm-openai?tab=readme-ov-file#contributing

**Comment by matthiasritter** [comment]
Hi @zioproto 
I have done everything as described in the instructions. Is there anything left todo from my side?
Thank you

**Comment by matthiasritter** [comment]
@zioproto Do you know, when this feature be released?

**Pull request merged**
